services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: corepack enable && pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
